from . import prescription
from . import appointment
from . import doctor
from . import patient
from . import medicine
from . import prescriptionline
from . import patientWeight
from . import hrEmployee
from . import medicalfile
